### ISSUE TITLE
The update to 2.2.4 caused some amd modules to be detected as commonjs

### ISSUE THREAD

**Issue by lellimecnar** [dependents/module-definition#24]
This file is being detected as commonjs:
https://github.com/moment/moment/blob/develop/moment.js

Reverting back to 2.2.3 fixed the problem

**Comment by mrjoelkemp** [comment]
Hey @lellimecnar! Thanks for filing the issue!

UMD files are interesting in that they're commonjs or amd depending on the environment. 

The 2.2.3 implementation searched through the entire file before determining the type – so the AMD `define` was found after the commonjs `module.exports`. Now, we stop searching as soon as we have enough information to determine the module type. 

Technically, we could interpret that file as CommonJS because that's the first import mechanism listed. That file being considered AMD is only a coincidence. 

So that I have a better understanding of your needs, in what way are you using `module-definition` that you need this file to be considered AMD?

cc @pahen

**Comment by lellimecnar** [comment]
I use it to determine if a file needs to be transpiled before running in
the browser. Is there any chance for adding "UMD" as a possible return
value?

**Comment by mrjoelkemp** [comment]
Thanks for clarifying @lellimecnar. It's definitely possible and a better option than choosing commonjs or amd based on which one is listed first. Are you open to creating that PR? I'd be happy to review it.

**Comment by mrjoelkemp** [comment]
@lellimecnar I've been thinking about this issue quite a bit. As much as I think a UMD type is clear, I'm not sure that I see the benefit that this would provide. 

From an implementation perspective, detecting the umd type would involve sniffing the entire file for both amd and commonjs import mechanisms. Sniffing the entire file/ast was a very time consuming operation (see https://github.com/dependents/module-definition/pull/23). Now, we stop when we've found the first identifiable import mechanism.

Looking at the [UMD variations](https://github.com/umdjs/umd/#variations), it seems that there are forms that would make the file be identified (if we continue to stop once we identify an import mechanism) as AMD over CommonJS. There are also other forms of UMD that do the opposite.

Taking a step back though, in your determination of whether or not a file needs to be transpiled, what does the module type have to do with this? Do you have an example repo for more details? I'd like to understand what you're going for to determine if there's a different path that avoids the need for UMD support.

**Comment by mrjoelkemp** [comment]
I'm open to a PR that introduces a flag to allow a deep search to determine if a file is of the UMD type. Happy to review such a PR. 

Alsi happy to reopen this if there's interest in continuing the discussion.
